=begin
#DPN API

#Digital Preservation Network

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MemberApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MemberApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MemberApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberApi' do
    it 'should create an instact of MemberApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MemberApi)
    end
  end

  # unit tests for member_get
  # List of members
  # Returns a list of members. 
  # @param page Page number to return, starting at 1.  For use  with page_size. 
  # @param page_size Max results per page. 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :before Only include records with updated_at **earlier**  than this, inclusive. 
  # @option opts [DateTime] :after Only include records with updated_at **later**  than this, inclusive. 
  # @option opts [Array<String>] :order_by Comma separated list of string fields by which to order the response. 
  # @return [MemberResultList]
  describe 'member_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for member_member_id_bags_get
  # Returns the member&#39;s bags
  # Returns the member&#39;s bags.  Behavior should match that of &#x60;&#x60;&#x60;/bags/?member&#x3D;&lt;member:member_id&gt;&#x60;&#x60;&#x60;, including querystring options except for &#x60;&#x60;&#x60;member&#x60;&#x60;&#x60;. 
  # @param member_id member_id of the member
  # @param [Hash] opts the optional parameters
  # @return [BagResultList]
  describe 'member_member_id_bags_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for member_member_id_get
  # Returns the data for a single member record matching the member_id.
  # Returns the data for a single member record matching the member_id.
  # @param member_id member_id of the member
  # @param [Hash] opts the optional parameters
  # @return [Member]
  describe 'member_member_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for member_member_id_put
  # Update the member
  # Updates a single member matching the member_id.  The body of the put is the same as the data structure for the member.  If successful, the response will be identical to that of a GET request. 
  # @param member_id member_id of the member
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Member]
  describe 'member_member_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for member_post
  # Create a member
  # This endpoint allows the creation of a single member through a post body.  The body is the same as the data structure for the Member. If successful, the response will be identical to that of a GET request. 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Member]
  describe 'member_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
