=begin
#DPN API

#Digital Preservation Network

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReplicateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReplicateApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReplicateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReplicateApi' do
    it 'should create an instact of ReplicateApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReplicateApi)
    end
  end

  # unit tests for replicate_get
  # List of replication requests
  # Returns a list of replication transfer requests. 
  # @param page Page number to return, starting at 1.  For use  with page_size. 
  # @param page_size Max results per page. 
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :before Only include records with updated_at **earlier**  than this, inclusive. 
  # @option opts [DateTime] :after Only include records with updated_at **later**  than this, inclusive. 
  # @option opts [Array<String>] :order_by Comma separated list of string fields by which to order the response. 
  # @option opts [String] :bag Filter by the associated bag&#39;s uuid 
  # @option opts [String] :to_node Filter by to_node namespace. 
  # @option opts [String] :from_node Filter by from_node namespace. 
  # @option opts [BOOLEAN] :store_requested Filter by store_requested 
  # @option opts [BOOLEAN] :stored Filter by stored 
  # @option opts [BOOLEAN] :cancelled Filter by cancelled 
  # @option opts [String] :cancel_reason Filter by cancel_reason.  Refer to the object definition for supported values. 
  # @return [ReplicationRequestResultList]
  describe 'replicate_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replicate_post
  # Create a replication request
  # This endpoint allows the creation of a single replication request through a post body.  The post body is the same as the data structure for the replication request.  If successful, the response will be identical to that of a GET request. 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ReplicationRequest]
  describe 'replicate_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replicate_replication_id_get
  # Returns the data for a single replication request.
  # Returns the data for a single replication transfer request record matching the replication_id. 
  # @param replication_id replication_id of the target record
  # @param [Hash] opts the optional parameters
  # @return [ReplicationRequest]
  describe 'replicate_replication_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replicate_replication_id_put
  # Update the replication request
  # Updates a single replication transfer request matching the replication_id.  The body of the put is the same as the data structure for the replication request.  If successful, the response will be identical to that of a GET request. 
  # @param replication_id replication_id of the target record
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ReplicationRequest]
  describe 'replicate_replication_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
