=begin
#DPN API

#Digital Preservation Network

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient
  # A DPN bag of any type
  class Bag
    # DPN-formatted date-time when this record was first created. _(read only)_ 
    attr_accessor :created_at

    # DPN-formatted date-time when this record was las updated. 
    attr_accessor :updated_at

    # Unique UUIDv4 identifier for this bag. _(read only)_
    attr_accessor :uuid

    # Primary local identifier.
    attr_accessor :local_id

    # Size of the bag in bytes. _(read only)_
    attr_accessor :size

    # UUID of the first version of this bag. _(read only)_
    attr_accessor :first_version_uuid

    # Namespace of the node that originally ingest this bag. _(read only)_
    attr_accessor :ingest_node

    # Namespace of the node that administers this bag.
    attr_accessor :admin_node

    # UUIDv4 of the member who \"owns\" this bag.
    attr_accessor :member

    # This bag's version number, beginning with 1. _(read only)_
    attr_accessor :version

    # Single character specifying the type of this bag. 'D'->Data, 'I'->Interpretive, 'R'->Rights. 
    attr_accessor :bag_type

    # Empty array or array of uuids of this bag's interpretive bags.
    attr_accessor :interpretive

    # Empty array or array of uuids of this bag's rights bags.
    attr_accessor :rights

    # Empty array or array of namespaces of this bag's replicating nodes.
    attr_accessor :replicating_nodes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'uuid' => :'uuid',
        :'local_id' => :'local_id',
        :'size' => :'size',
        :'first_version_uuid' => :'first_version_uuid',
        :'ingest_node' => :'ingest_node',
        :'admin_node' => :'admin_node',
        :'member' => :'member',
        :'version' => :'version',
        :'bag_type' => :'bag_type',
        :'interpretive' => :'interpretive',
        :'rights' => :'rights',
        :'replicating_nodes' => :'replicating_nodes'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime',
        :'uuid' => :'String',
        :'local_id' => :'String',
        :'size' => :'Integer',
        :'first_version_uuid' => :'String',
        :'ingest_node' => :'String',
        :'admin_node' => :'String',
        :'member' => :'String',
        :'version' => :'Integer',
        :'bag_type' => :'String',
        :'interpretive' => :'Array<String>',
        :'rights' => :'Array<String>',
        :'replicating_nodes' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.has_key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.has_key?(:'local_id')
        self.local_id = attributes[:'local_id']
      end

      if attributes.has_key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.has_key?(:'first_version_uuid')
        self.first_version_uuid = attributes[:'first_version_uuid']
      end

      if attributes.has_key?(:'ingest_node')
        self.ingest_node = attributes[:'ingest_node']
      end

      if attributes.has_key?(:'admin_node')
        self.admin_node = attributes[:'admin_node']
      end

      if attributes.has_key?(:'member')
        self.member = attributes[:'member']
      end

      if attributes.has_key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.has_key?(:'bag_type')
        self.bag_type = attributes[:'bag_type']
      end

      if attributes.has_key?(:'interpretive')
        if (value = attributes[:'interpretive']).is_a?(Array)
          self.interpretive = value
        end
      end

      if attributes.has_key?(:'rights')
        if (value = attributes[:'rights']).is_a?(Array)
          self.rights = value
        end
      end

      if attributes.has_key?(:'replicating_nodes')
        if (value = attributes[:'replicating_nodes']).is_a?(Array)
          self.replicating_nodes = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @version.nil?
        invalid_properties.push("invalid value for 'version', version cannot be nil.")
      end

      if @version < 1.0
        invalid_properties.push("invalid value for 'version', must be greater than or equal to 1.0.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @uuid.nil?
      return false if @local_id.nil?
      return false if @size.nil?
      return false if @first_version_uuid.nil?
      return false if @ingest_node.nil?
      return false if @admin_node.nil?
      return false if @member.nil?
      return false if @version.nil?
      return false if @version < 1.0
      return false if @bag_type.nil?
      bag_type_validator = EnumAttributeValidator.new('String', ["D", "I", "R"])
      return false unless bag_type_validator.valid?(@bag_type)
      return false if @interpretive.nil?
      return true
    end

    # Custom attribute writer method with validation
    # @param [Object] version Value to be assigned
    def version=(version)
      if version.nil?
        fail ArgumentError, "version cannot be nil"
      end

      if version < 1.0
        fail ArgumentError, "invalid value for 'version', must be greater than or equal to 1.0."
      end

      @version = version
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bag_type Object to be assigned
    def bag_type=(bag_type)
      validator = EnumAttributeValidator.new('String', ["D", "I", "R"])
      unless validator.valid?(bag_type)
        fail ArgumentError, "invalid value for 'bag_type', must be one of #{validator.allowable_values}."
      end
      @bag_type = bag_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          uuid == o.uuid &&
          local_id == o.local_id &&
          size == o.size &&
          first_version_uuid == o.first_version_uuid &&
          ingest_node == o.ingest_node &&
          admin_node == o.admin_node &&
          member == o.member &&
          version == o.version &&
          bag_type == o.bag_type &&
          interpretive == o.interpretive &&
          rights == o.rights &&
          replicating_nodes == o.replicating_nodes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [created_at, updated_at, uuid, local_id, size, first_version_uuid, ingest_node, admin_node, member, version, bag_type, interpretive, rights, replicating_nodes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
