=begin
#DPN API

#Digital Preservation Network

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module SwaggerClient
  # A DPN node
  class Node
    # DPN-formatted date-time when this record was first created. _(read only)_ 
    attr_accessor :created_at

    # DPN-formatted date-time when this record was las updated. 
    attr_accessor :updated_at

    # Human readable name of this node 
    attr_accessor :name

    # Lowercase identifier to unambiguously reference this node. 
    attr_accessor :namespace

    # null or the root location of this node's server. This field MUST NOT be changed during normal operations; it should only change out of band. 
    attr_accessor :api_root

    # null or the ssh public key of this node. 
    attr_accessor :ssh_pubkey

    # Array of namespaces of the nodes that this node will replicate from. 
    attr_accessor :replicate_from

    # Array of namespaces of the nodes that this node will replicate to. 
    attr_accessor :replciate_to

    # Array of namespaces of the nodes that this node will restore from. 
    attr_accessor :restore_from

    # Array of namespaces of the nodes that this node will restore to. 
    attr_accessor :restore_to

    # Array of currently supported transfer protocols. 
    attr_accessor :protocols

    # Array of currently supported fixity algorithms. 
    attr_accessor :fixity_algorithms

    # Storage profile for this node.
    attr_accessor :storage


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'name' => :'name',
        :'namespace' => :'namespace',
        :'api_root' => :'api_root',
        :'ssh_pubkey' => :'ssh_pubkey',
        :'replicate_from' => :'replicate_from',
        :'replciate_to' => :'replciate_to',
        :'restore_from' => :'restore_from',
        :'restore_to' => :'restore_to',
        :'protocols' => :'protocols',
        :'fixity_algorithms' => :'fixity_algorithms',
        :'storage' => :'storage'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'created_at' => :'DateTime',
        :'updated_at' => :'DateTime',
        :'name' => :'String',
        :'namespace' => :'String',
        :'api_root' => :'String',
        :'ssh_pubkey' => :'String',
        :'replicate_from' => :'Array<String>',
        :'replciate_to' => :'Array<String>',
        :'restore_from' => :'Array<String>',
        :'restore_to' => :'Array<String>',
        :'protocols' => :'Array<String>',
        :'fixity_algorithms' => :'Array<String>',
        :'storage' => :'Object'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.has_key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'namespace')
        self.namespace = attributes[:'namespace']
      end

      if attributes.has_key?(:'api_root')
        self.api_root = attributes[:'api_root']
      end

      if attributes.has_key?(:'ssh_pubkey')
        self.ssh_pubkey = attributes[:'ssh_pubkey']
      end

      if attributes.has_key?(:'replicate_from')
        if (value = attributes[:'replicate_from']).is_a?(Array)
          self.replicate_from = value
        end
      end

      if attributes.has_key?(:'replciate_to')
        if (value = attributes[:'replciate_to']).is_a?(Array)
          self.replciate_to = value
        end
      end

      if attributes.has_key?(:'restore_from')
        if (value = attributes[:'restore_from']).is_a?(Array)
          self.restore_from = value
        end
      end

      if attributes.has_key?(:'restore_to')
        if (value = attributes[:'restore_to']).is_a?(Array)
          self.restore_to = value
        end
      end

      if attributes.has_key?(:'protocols')
        if (value = attributes[:'protocols']).is_a?(Array)
          self.protocols = value
        end
      end

      if attributes.has_key?(:'fixity_algorithms')
        if (value = attributes[:'fixity_algorithms']).is_a?(Array)
          self.fixity_algorithms = value
        end
      end

      if attributes.has_key?(:'storage')
        self.storage = attributes[:'storage']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @namespace.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          name == o.name &&
          namespace == o.namespace &&
          api_root == o.api_root &&
          ssh_pubkey == o.ssh_pubkey &&
          replicate_from == o.replicate_from &&
          replciate_to == o.replciate_to &&
          restore_from == o.restore_from &&
          restore_to == o.restore_to &&
          protocols == o.protocols &&
          fixity_algorithms == o.fixity_algorithms &&
          storage == o.storage
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [created_at, updated_at, name, namespace, api_root, ssh_pubkey, replicate_from, replciate_to, restore_from, restore_to, protocols, fixity_algorithms, storage].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
